#!/usr/bin/env python3
"""Turn the captured layout.json into a Plasma layout script (JavaScript).

Usage: make-layout.py <layout.json> <wallpaper path or ""> > layout.js
The script replaces all panels with the captured ones on the primary screen and
puts the captured desktop widgets and wallpaper back.
"""
import json
import sys

layout = json.loads(open(sys.argv[1]).read())
wallpaper = sys.argv[2] if len(sys.argv) > 2 else ""


def unescape(value):
    """KConfig escapes (\\\\, \\s, \\t, \\n) back to plain text; writeConfig escapes again."""
    out, i = [], 0
    while i < len(value):
        c = value[i]
        if c == "\\" and i + 1 < len(value):
            nxt = value[i + 1]
            out.append({"\\": "\\", "s": " ", "t": "\t", "n": "\n"}.get(nxt, "\\" + nxt))
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


js = ["// Generated by the RBR kit. Replaces panels on the primary screen.",
      "var screen = 0;",
      "panels().forEach(function (p) { if (p.screen === screen) p.remove(); });",
      "function configure(w, cfg) {",
      "    for (var group in cfg) {",
      "        w.currentConfigGroup = group.split('/');",
      "        for (var key in cfg[group]) w.writeConfig(key, cfg[group][key]);",
      "    }",
      "    w.reloadConfig();",
      "}"]


def applet_js(target, applet, geometry=None):
    cfg = {g: {k: unescape(v) for k, v in kv.items()} for g, kv in applet.get("config", {}).items()}
    lines = []
    if geometry:
        x, y, w, h = geometry
        lines.append(f"var w = {target}.addWidget({json.dumps(applet['plugin'])}, {x}, {y}, {w}, {h});")
    else:
        lines.append(f"var w = {target}.addWidget({json.dumps(applet['plugin'])});")
    lines.append("if (w) {")
    if cfg:
        lines.append(f"    configure(w, {json.dumps(cfg)});")
    if applet.get("trayGeneral") and "General" not in cfg:
        tray = {"General": {k: unescape(v) for k, v in applet["trayGeneral"].items()}}
        lines.append(f"    configure(w, {json.dumps(tray)});")
    if applet.get("shortcut"):
        lines.append(f"    w.globalShortcut = {json.dumps(applet['shortcut'])};")
    lines.append("}")
    return lines


for i, panel in enumerate(layout["panels"]):
    props = panel.get("props", {})
    js += ["", f"// {panel['location']} panel",
           "var p = new Panel('org.kde.panel');",
           f"p.location = {json.dumps(panel['location'])};",
           f"p.height = {int(props.get('height', panel['thickness']))};"]
    for key in ("opacity", "lengthMode", "alignment", "hiding"):
        if key in props:
            js.append(f"try {{ p.{key} = {json.dumps(props[key])}; }} catch (e) {{}}")
    if "floating" in props:
        js.append(f"try {{ p.floating = {str(bool(props['floating'])).lower()}; }} catch (e) {{}}")
    for applet in panel["applets"]:
        js += applet_js("p", applet)
    js.append("print('panel ' + p.id + ' ' + p.location + '\\n');")

desktop = layout.get("desktop", {})
js += ["", "// desktop", "var d = desktopForScreen(screen);"]
if wallpaper:
    js += ["d.wallpaperPlugin = 'org.kde.image';",
           "d.currentConfigGroup = ['Wallpaper', 'org.kde.image', 'General'];",
           f"d.writeConfig('Image', {json.dumps('file://' + wallpaper)});"]
for applet in desktop.get("applets", []):
    js.append(f"d.widgets({json.dumps(applet['plugin'])}).forEach(function (w) {{ w.remove(); }});")
    js += applet_js("d", applet, applet.get("geometry"))
js.append("print('desktop done\\n');")
print("\n".join(line for line in js if line != ""))
